BLOCK_EXPLOSION: '7'
CONTACT: '8'
CRAMMING: '0'
DRAGON_BREATH: '5'
DROWNING: '3'
DRYOUT: '9'
ENTITY_ATTACK: '4'
ENTITY_EXPLOSION: '7'
ENTITY_SWEEP_ATTACK: e
FALL: f
FALLING_BLOCK: f
FIRE: '6'
FIRE_TICK: '6'
FLY_INTO_WALL: '8'
HOT_FLOOR: '6'
LAVA: '6'
LIGHTNING: d
MAGIC: '5'
POISON: '2'
PROJECTILE: '8'
STARVATION: e
SUFFOCATION: '0'
SUICIDE: '0'
THORNS: '0'
VOID: '0'
WITHER: '0'
CUSTOM: a
another: f
